try to get npm install working

diff --git a/customize b/customize
--- a/customize
+++ b/customize
@@ -35,18 +35,27 @@ n 8.11.4
 # sudo apt-get update && sudo apt-get install yarn
 
 echo "* Setup rocket-chat"
+addgroup rocket
 adduser --disabled-password --system --quiet --home /var/www/rocket rocket
+adduser rocket rocket
 mkdir -p /var/www/rocket
 curl -L -s https://releases.rocket.chat/latest/download | tar xz -C /var/www/rocket --strip-components=1
 cd /var/www/rocket
-# (cd programs/server && npm install)
-# chown -R rocket:rocket /var/www/rocket*
+# this might fail so let it go...
+set +o errexit
+(cd programs/server && npm install)
+set -o errexit
+chown -R rocket:rocket /var/www/rocket*
 
 echo "* Setup rocket-chat service"
 cp /usr/local/var/tmp/rocketchat.service /etc/systemd/system/rocketchat.service
-# systemctl daemon-reload
-# systemctl enable rocketchat.service
-# systemctl start rocketchat
+
+echo "* We may use mongodb locally"
+cat <<EOF >> /etc/mongodb.conf
+
+replication:
+  replSetName:  "001-rs"
+EOF
 
 echo "* Cleaning up."
 rm -rf /usr/local/var/tmp/*
