fix mongo 4.2 installation option

diff --git a/customize b/customize
--- a/customize
+++ b/customize
@@ -45,8 +45,16 @@ systemctl daemon-reload
 # service nginx restart
 
 echo "* Setup mongodb v${MONGO_VERSION}"
-curl -fsSL https://www.mongodb.org/static/pgp/server-${MONGO_VERSION}.asc | apt-key add - || true
-echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/${MONGO_VERSION} multiverse" | tee /etc/apt/sources.list.d/mongodb-org-${MONGO_VERSION}.list
+if [[ "${MONGO_VERSION}" = "4.2" ]]; then
+  curl -fsSL https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add - || true
+  echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list
+elif [[ "${MONGO_VERSION}" = "4.4" ]]; then
+  curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - || true
+  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
+else
+  echo "ERROR: mongodb-version not found"
+  exit 1
+fi
 
 apt-get -y update
 apt-get -y install mongodb-org
